---
title: "Cases per day"
output: html_notebook
---

## Load packages
```{r}
library(tidyverse)
library(zoo) # for rolling averages
library(readxl)
```

## Load data
```{r}
# Cases data
cases <- read_csv('data/cleaned_cases.csv')

# Restriction data
timeline <- read_excel('data/restrictions.xlsx') %>% 
  mutate(Date_start = as.Date(Date_start)) %>% 
  mutate(Date_end = as.Date(Date_end)) %>% 
  pivot_longer(cols = Toronto:Halton, names_to = 'Region', values_to = 'Restrictions') %>% 
  mutate(Restrictions = factor(Restrictions, 
                               levels = c("Enhanced lockdown", "Lockdown/Stage 1", "Red/Stage 2/Modified Stage 2", "Green/Stage 3", "Orange/Gathering limits")))
```

## Timeline
```{r}
Durham <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-11-23', '2020-12-26', '2021-02-16'))
Halton <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-12-26', '2021-02-16'))
Peel <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
Toronto <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
York <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-10-19', '2020-11-07', '2020-11-16', '2020-12-14', '2020-12-26', '2021-02-22'))

breakpoints <- timeline %>% 
  filter((Region == 'Durham' & Date_start %in% Durham) |
         (Region == 'Halton' & Date_start %in% Halton) |
         (Region == 'Peel' & Date_start %in% Peel) |
         (Region == 'Toronto' & Date_start %in% Toronto) |
         (Region == 'York' & Date_start %in% York))
```

## Roll mean and tidy data
```{r}
tidy_cases <- cases %>% 
  pivot_longer(cols = Durham:York, 
               names_to = 'Region', values_to = 'Cases per day')

rollmean <- cases %>% 
  mutate(across(where(is.numeric), ~ rollmean(., k = 7, fill = NA))) %>% 
  pivot_longer(cols = Durham:York, 
               names_to = 'Region', values_to = 'Cases per day') %>% 
  filter(Date >= '2020-03-16')
```

## Color scale
```{r}
fill <- c("Enhanced lockdown"='gray33', "Lockdown/Stage 1"='gray66', "Red/Stage 2/Modified Stage 2"='red', "Green/Stage 3"='green', "Orange/Gathering limits"='orange')
```

## Graphs
```{r}
cases_plot <- ggplot() +
  geom_bar(tidy_cases, mapping=aes(x=Date, y=`Cases per day`), stat="identity") +
  geom_line(rollmean, mapping=aes(x=Date, y=`Cases per day`), color='blue') +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  geom_vline(breakpoints,
             mapping = aes(xintercept=Date_start),
             linetype = 'dashed') +
  scale_fill_manual(values=fill) +
  scale_x_date(date_breaks = "1 month") +
  facet_grid(rows=vars(Region)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

ggsave('graphs/cases.png', cases_plot, height = 8.5, width = 11, units = 'in')

cases_plot
```