---
title: "Mobility"
output: html_notebook
---

## Load packages
```{r}
library(tidyverse)
library(zoo) # for rolling averages
library(readxl)
```

## Read data
```{r}
# Restriction data
timeline <- read_excel('data/restrictions.xlsx') %>% 
  mutate(Date_start = as.Date(Date_start)) %>% 
  mutate(Date_end = as.Date(Date_end)) %>% 
  pivot_longer(cols = Toronto:Halton, names_to = 'Region', values_to = 'Restrictions') %>% 
  mutate(Restrictions = factor(Restrictions, 
                               levels = c("Enhanced lockdown", "Lockdown/Stage 1", "Red/Stage 2/Modified Stage 2", "Green/Stage 3", "Orange/Gathering limits")))

# Mobility data
regions = c('Regional Municipality of Durham', 'Regional Municipality of Halton', 'Regional Municipality of Peel', 'Toronto Division', 'Regional Municipality of York')
mob <- read_csv('data/2020_CA_Region_Mobility_Report.csv') %>% 
  rename(Retail=retail_and_recreation_percent_change_from_baseline,
         Grocery=grocery_and_pharmacy_percent_change_from_baseline,
         Parks=parks_percent_change_from_baseline,
         Transit=transit_stations_percent_change_from_baseline,
         Workplaces=workplaces_percent_change_from_baseline,
         Residential=residential_percent_change_from_baseline) %>% 
  select(sub_region_2, date, 
         Retail, Grocery, Parks, Transit, Workplaces, Residential) %>% 
  filter(sub_region_2 %in% regions) %>% 
  mutate(Global = (Retail + Grocery + Parks + Transit + Workplaces + Residential)/6)%>%
  rename(Region=sub_region_2, Date=date) %>% 
  mutate(Region = case_when(Region == 'Regional Municipality of Durham' ~ 'Durham',
                            Region == 'Regional Municipality of Halton' ~ 'Halton',
                            Region == 'Regional Municipality of Peel' ~ 'Peel',
                            Region == 'Toronto Division' ~ 'Toronto',
                            Region == 'Regional Municipality of York' ~ 'York'))
```

## Roll mean and tidy data
```{r}
tidy_mob <- mob %>% 
  pivot_longer(cols = Retail:Global, 
               names_to = 'Mobility type', values_to = 'Mobility change (%)')

rollmean <- mob %>% 
  mutate(across(where(is.numeric), ~ rollmean(., k = 7, fill = NA))) %>% 
  pivot_longer(cols = Retail:Global, 
               names_to = 'Mobility type', values_to = 'Mobility change (%)')
```

## Timeline
```{r}
Durham <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-11-23', '2020-12-26', '2021-02-16'))
Halton <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-12-26', '2021-02-16'))
Peel <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
Toronto <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
York <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-10-19', '2020-11-07', '2020-11-16', '2020-12-14', '2020-12-26', '2021-02-22'))

breakpoints <- timeline %>% 
  filter((Region == 'Durham' & Date_start %in% Durham) |
         (Region == 'Halton' & Date_start %in% Halton) |
         (Region == 'Peel' & Date_start %in% Peel) |
         (Region == 'Toronto' & Date_start %in% Toronto) |
         (Region == 'York' & Date_start %in% York))
```

## Global mobility data
```{r}
fill <- c("Enhanced lockdown"='gray33', "Lockdown/Stage 1"='gray66', "Red/Stage 2/Modified Stage 2"='red', "Green/Stage 3"='green', "Orange/Gathering limits"='orange')

global <- ggplot() +
  geom_line(tidy_mob %>% filter(`Mobility type` == 'Global'),
            mapping = aes(x=Date,y=`Mobility change (%)`)) +
  geom_line(rollmean %>% filter(`Mobility type` == 'Global'),
            mapping = aes(x=Date,y=`Mobility change (%)`),
            color = 'blue') +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  geom_vline(breakpoints,
             mapping = aes(xintercept=Date_start),
             linetype = 'dashed') +
  ylab('Global mobility change (%)') +
  scale_fill_manual(values=fill) +
  scale_x_date(date_breaks = "1 month") +
  facet_grid(rows=vars(Region)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

ggsave('graphs/global_mobility.png', global, height = 8.5, width = 11, units = 'in')

global
```


## Mobility data
```{r}
col <- c('Grocery'='red', 'Parks'='blue', 'Residential'='cyan', 'Retail'='darkgreen', 'Transit'='pink', 'Workplaces'='seagreen1')

mobility <- ggplot() +
  geom_line(tidy_mob %>% filter(`Mobility type` != 'Global'), 
            mapping = aes(x=Date,y=`Mobility change (%)`,color=`Mobility type`)) +
  # geom_line(rollmean %>% filter(`Mobility type` != 'Global'), 
  #           mapping = aes(x=Date,y=`Mobility change (%)`,color=`Mobility type`)) +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  geom_vline(breakpoints,
             mapping = aes(xintercept=Date_start),
             linetype = 'dashed') +
  scale_fill_manual(values=fill) +
  scale_color_manual(values = col) +
  scale_x_date(date_breaks = "1 month") +
  facet_grid(rows=vars(Region)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

ggsave('graphs/mobility.png', mobility, height = 8.5, width = 11, units = 'in')

mobility
```
