---
title: "Estimated Rt"
output: html_notebook
---

## Load packages
```{r}
library(tidyverse)
library(EpiEstim)
```

## Load data
```{r}
# assume that missing data means zero cases for that day

data <- read_csv('data/daily_change_in_cases_by_phu.csv') %>% 
  select(Date, Durham_Region_Health_Department, Halton_Region_Health_Department, Peel_Public_Health, Toronto_Public_Health, York_Region_Public_Health_Services) %>% 
  rename(Durham=Durham_Region_Health_Department, Halton=Halton_Region_Health_Department, Peel=Peel_Public_Health, Toronto=Toronto_Public_Health, York=York_Region_Public_Health_Services) %>% 
  replace(is.na(.), 0)

write_csv(data, 'data/cleaned_data.csv')
```

```{r}
# replace negative counts with zero

rt_data <- data %>% 
  mutate(across(where(is.numeric), ~ replace(., .<0, 0)))
write_csv(rt_data, 'estR/rt_calc_data.csv')
```


## Make df's for R calculation
```{r}
toronto <- rt_data %>% 
  select(Date, Toronto) %>% 
  rename(dates=Date, I=Toronto)
peel <- rt_data %>% 
  select(Date, Peel) %>% 
  rename(dates=Date, I=Peel)
york <- rt_data %>% 
  select(Date, York) %>% 
  rename(dates=Date, I=York)
durham <- rt_data %>% 
  select(Date, Durham) %>% 
  rename(dates=Date, I=Durham)
halton <- rt_data %>% 
  select(Date, Halton) %>% 
  rename(dates=Date, I=Halton)
```

## Calculate Rt
```{r}
tr <- estimate_R(toronto, method = 'parametric_si',
           config = make_config(list(mean_si = 5.2, std_si = 5.1)))
pr <- estimate_R(peel, method = 'parametric_si',
           config = make_config(list(mean_si = 5.2, std_si = 5.1)))
yr <- estimate_R(york, method = 'parametric_si',
           config = make_config(list(mean_si = 5.2, std_si = 5.1)))
dr <- estimate_R(durham, method = 'parametric_si',
           config = make_config(list(mean_si = 5.2, std_si = 5.1)))
hr <- estimate_R(halton, method = 'parametric_si',
           config = make_config(list(mean_si = 5.2, std_si = 5.1)))
```

## Toronto
```{r}
plot(tr, 'R')
```

## Peel
```{r}
plot(pr, 'R')
```

## York
```{r}
plot(yr, 'R')
```

## Durham
```{r}
plot(dr, 'R')
```

## Halton
```{r}
plot(hr, 'R')
```

```{r, include=FALSE}
# Save plots

png('estR/Toronto_R.png', 
    width=11,
    height=8.5,
    units='in',
    res = 144)
plot(tr, 'R')
dev.off()

png('estR/Peel_R.png', 
    width=11,
    height=8.5,
    units='in',
    res = 144)
plot(pr, 'R')
dev.off()

png('estR/York_R.png', 
    width=11,
    height=8.5,
    units='in',
    res = 144)
plot(yr, 'R')
dev.off()

png('estR/Durham_R.png', 
    width=11,
    height=8.5,
    units='in',
    res = 144)
plot(dr, 'R')
dev.off()

png('estR/Halton_R.png', 
    width=11,
    height=8.5,
    units='in',
    res = 144)
plot(hr, 'R')
dev.off()
```

## Get data in usable form
```{r}
tr <- tr$R %>% add_column(date_start = tr$dates[tr$R$t_start],
                          date_end = tr$dates[tr$R$t_end])
pr <- pr$R %>% add_column(date_start = pr$dates[pr$R$t_start],
                          date_end = pr$dates[pr$R$t_end])
yr <- yr$R %>% add_column(date_start = yr$dates[yr$R$t_start],
                          date_end = yr$dates[yr$R$t_end])
dr <- dr$R %>% add_column(date_start = dr$dates[dr$R$t_start],
                          date_end = dr$dates[dr$R$t_end])
hr <- hr$R %>% add_column(date_start = hr$dates[hr$R$t_start],
                          date_end = hr$dates[hr$R$t_end])

```

## Write csv's
```{r}
write_csv(tr, 'estR/toronto_R.csv')
write_csv(pr, 'estR/peel_R.csv')
write_csv(yr, 'estR/york_R.csv')
write_csv(dr, 'estR/durham_R.csv')
write_csv(hr, 'estR/halton_R.csv')
```

