---
title: "R Notebook"
output: html_notebook
---

## Load packages
```{r}
library(tidyverse)
library(segmented)
library(zoo) # for rolling averages
library(readxl)
library(ggpubr)
library(ggrepel)
```

## Read data
```{r}
# Restriction data
timeline <- read_excel('data/restrictions.xlsx') %>% 
  mutate(Date_start = as.Date(Date_start)) %>% 
  mutate(Date_end = as.Date(Date_end)) %>% 
  pivot_longer(cols = Toronto:Halton, names_to = 'Region', values_to = 'Restrictions')

# Mobility data
regions = c('Regional Municipality of Durham', 'Regional Municipality of Halton', 'Regional Municipality of Peel', 'Toronto Division', 'Regional Municipality of York')
mob <- read_csv('data/2020_CA_Region_Mobility_Report.csv') %>% 
  rename(Retail=retail_and_recreation_percent_change_from_baseline,
         Grocery=grocery_and_pharmacy_percent_change_from_baseline,
         Parks=parks_percent_change_from_baseline,
         Transit=transit_stations_percent_change_from_baseline,
         Workplaces=workplaces_percent_change_from_baseline,
         Residential=residential_percent_change_from_baseline) %>% 
  select(sub_region_2, date, 
         Retail, Grocery, Parks, Transit, Workplaces, Residential) %>% 
  filter(sub_region_2 %in% regions) %>% 
  mutate(Global = (Retail + Grocery + Parks + Transit + Workplaces + Residential)/6)%>%
  rename(Region=sub_region_2, Date=date) %>% 
  mutate(Region = case_when(Region == 'Regional Municipality of Durham' ~ 'Durham',
                            Region == 'Regional Municipality of Halton' ~ 'Halton',
                            Region == 'Regional Municipality of Peel' ~ 'Peel',
                            Region == 'Toronto Division' ~ 'Toronto',
                            Region == 'Regional Municipality of York' ~ 'York'))
```

## Roll mean and tidy data
```{r}
tidy_mob <- mob %>% 
  pivot_longer(cols = Retail:Global, 
               names_to = 'Mobility type', values_to = 'Mobility change (%)')

rollmean <- mob %>% 
  mutate(across(where(is.numeric), ~ rollmean(., k = 7, fill = NA))) %>% 
  pivot_longer(cols = Retail:Global, 
               names_to = 'Mobility type', values_to = 'Mobility change (%)')
```

## Global mobility data
```{r}
fill <- c("Lockdown"='gray33', "Stage 1/Red"='gray66', "Stage 2/Modified Stage 2/Orange"='red', "Stage 3/ Yellow"='green', "Gathering limits"='orange')

global <- ggplot() +
  geom_line(tidy_mob %>% filter(`Mobility type` == 'Global'),
            mapping = aes(x=Date,y=`Mobility change (%)`)) +
  geom_line(rollmean %>% filter(`Mobility type` == 'Global'),
            mapping = aes(x=Date,y=`Mobility change (%)`)) +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  ylab('Global mobility change (%)') +
  scale_fill_manual(values=fill) +
  facet_grid(rows=vars(Region)) +
  theme_bw()

ggsave('graphs/global_mobility.png', global, height = 8.5, width = 11, units = 'in')

global
```


## Mobility data
```{r}
col <- c('Grocery'='red', 'Parks'='blue', 'Residential'='cyan', 'Retail'='darkgreen', 'Transit'='pink', 'Workplaces'='seagreen1')

mobility <- ggplot() +
  geom_line(tidy_mob %>% filter(`Mobility type` != 'Global'), 
            mapping = aes(x=Date,y=`Mobility change (%)`,color=`Mobility type`)) +
  # geom_line(rollmean %>% filter(`Mobility type` != 'Global'), 
  #           mapping = aes(x=Date,y=`Mobility change (%)`,color=`Mobility type`)) +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  scale_fill_manual(values=fill) +
  scale_color_manual(values=col) +
  facet_grid(rows=vars(Region)) +
  theme_bw()

ggsave('graphs/mobility.png', mobility, height = 8.5, width = 11, units = 'in')

mobility
```


