---
title: "Segmentation Analysis"
output: html_notebook
---

## Load packages
```{r, warning=F, message=F}
library(tidyverse)
library(readxl)
library(segmented)
```

## Read data
```{r}
# Restriction data
timeline <- read_excel('data/restrictions.xlsx') %>% 
  mutate(Date_start = as.Date(Date_start)) %>% 
  mutate(Date_end = as.Date(Date_end)) %>% 
  pivot_longer(cols = Toronto:Halton, names_to = 'Region', values_to = 'Restrictions') %>% 
  mutate(Restrictions = factor(Restrictions, 
                               levels = c("Enhanced lockdown", "Lockdown/Stage 1", "Red/Stage 2/Modified Stage 2", "Green/Stage 3", "Orange/Gathering limits")))

# Rt data
rt <- read_csv('estR/estR.csv') %>% 
  select(`Mean(R)`, date_start, Region) %>% 
  rename(Rt=`Mean(R)`, Date=date_start)
```

## Timeline
```{r}
Durham <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-11-23', '2020-12-26', '2021-02-16'))
Halton <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-11-16', '2020-12-26', '2021-02-16'))
Peel <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
Toronto <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-24', '2020-07-31', '2020-09-18', '2020-10-10', '2020-11-23', '2020-12-26', '2021-03-19'))
York <- as.Date(c('2020-03-17', '2020-05-19', '2020-06-19', '2020-07-24', '2020-10-19', '2020-11-07', '2020-11-16', '2020-12-14', '2020-12-26', '2021-02-22'))

breakpoints <- timeline %>% 
  filter((Region == 'Durham' & Date_start %in% Durham) |
         (Region == 'Halton' & Date_start %in% Halton) |
         (Region == 'Peel' & Date_start %in% Peel) |
         (Region == 'Toronto' & Date_start %in% Toronto) |
         (Region == 'York' & Date_start %in% York))
```

## Segmented Regression
```{r}
x <- rt %>% filter(Region=='Toronto')
my.lm <- lm(Rt ~ Date, data = x)
# make segmented regression
my.seg <- segmented(my.lm,
                    seg.Z = ~ Date)
my.fitted <- fitted(my.seg)
my.model <- data.frame(Date = x$Date, 
                       Rt = my.fitted)
```

```{r}
fill <- c("Enhanced lockdown"='gray33', "Lockdown/Stage 1"='gray66', "Red/Stage 2/Modified Stage 2"='red', "Green/Stage 3"='green', "Orange/Gathering limits"='orange')

ggplot() +
  geom_line(x,
            mapping = aes(x=Date,y=Rt)) +
  geom_line(my.model,
            mapping = aes(x=Date,y=Rt),
            color='blue') +
  geom_rect(timeline %>% filter(Region == 'Toronto'), 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  geom_vline(breakpoints %>% filter(Region == 'Toronto'),
             mapping = aes(xintercept=Date_start),
             linetype = 'dashed') +
  scale_fill_manual(values=fill) +
  theme_bw()
```


## Graphs
```{r}
fill <- c("Enhanced lockdown"='gray33', "Lockdown/Stage 1"='gray66', "Red/Stage 2/Modified Stage 2"='red', "Green/Stage 3"='green', "Orange/Gathering limits"='orange')

ggplot() +
  geom_line(rt,
            mapping = aes(x=Date,y=Rt)) +
  geom_rect(timeline, 
            mapping=aes(xmin=Date_start, xmax=Date_end, fill=Restrictions),
            ymin=-Inf, ymax=Inf, alpha=0.3) +
  geom_vline(breakpoints,
             mapping = aes(xintercept=Date_start),
             linetype = 'dashed') +
  scale_fill_manual(values=fill) +
  facet_grid(rows=vars(Region)) +
  theme_bw()
```

